[package]
name = "lockdiff"
version = "1.1.1"
description = "Display more readable diffs for lock files"
edition = "2021"
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/your-tools/lockdiff"


[dependencies]
anyhow = "1.0.58"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
toml = "0.5.9"
yarn-lock-parser = "0.6.0"
