[package]
name = "lockdiff"
version = "1.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
toml = "0.5.9"
yarn-lock-parser = "0.6.0"
